server:
  port: 8085

spring:
  application:
    name: data-transform-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  rabbit:
    queue: transform.queue

management:
  endpoints:
    web:
      exposure:
        include: health
